[build]
  command = "make build_linux_lambda"
  functions = "release/linux/lambda"

[build.environment]
  GO_VERSION = "1.20"
  GO_IMPORT_PATH = "github.com/tolki-app/gorush"
  GO111MODULE = "on"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/gorush/:splat"
  status = 200
