name: gorush
version: '1.0'
summary: A push notification server written in Go 
description: |
  A push notification server written in Go. 
grade: stable
confinement: strict
base: core18
parts:
  gorush:
    plugin: go
    source: https://github.com/tolki-app/gorush.git
    go-importpath: github.com/tolki-app/gorush
    build-packages:
      - build-essential
apps:
  gorush:
    command: bin/gorush
    daemon: simple
    restart-condition: on-abnormal
    plugs:
      - home
      - network
      - network-bind
